/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buildtools.gradle;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * @param args
     * @throws IOException 
     */
    public static void main(String[] args) throws IOException {
        
        // Start Calculator
        try {
            String jarFileName = "calculator-1.2.jar"; // The name of the jar file
            ProcessBuilder processBuilder = new ProcessBuilder("java", "-jar", jarFileName);
            
            // Start the process
            Process process = processBuilder.start();
            
            // If you want to capture and print the output of the jar application
            new Thread(() -> {
                BufferedReader input = new BufferedReader(new InputStreamReader(process.getInputStream()));
                input.lines().forEach(System.out::println);
            }).start();
            
            // Wait for the process to exit and print its exit code
            int exitCode = process.waitFor();
            System.out.println("Exited with code: " + exitCode);
            
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }  
        // Workaround: Navigate to the folder of gradle cache and start the calculator by "java -jar calculator-1.2.jar"
        // "C:\Users\USERNAME\.gradle\caches\modules-2\files-2.1\com.github.javadev\calculator\1.2\d1736e40b418c209b147497cc6f457e3e300ee33" 

        // PDF Box
        // example code from https://carbonrider.github.io/pdfbox_tutorial/introduction.html
        PDDocument helloPdf = new PDDocument();
        PDPage page = new PDPage(PDRectangle.A4);
        helloPdf.addPage(page);

        PDPageContentStream contentStream = new PDPageContentStream(helloPdf, page);
        contentStream.beginText();
        contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 36);
        contentStream.newLineAtOffset(10, 600);
        contentStream.showText("Hello DevOps ZHAW BuildTools!!!");
        contentStream.endText();
        contentStream.close();

        // helloPdf.save(new File("mysecondfile.pdf"));
        helloPdf.close();   
        
        // Pseudo Code
		IRender render = new Render();
		IContextBuilder builder = render.newBuilder();
		builder.width(120).height(20);
		builder.element(new PseudoText("DevOps <3"));
		ICanvas canvas = render.render(builder.build());
		String s = canvas.getText();
		System.out.println(s);

        System.out.println(new App().getGreeting());
    }
}
